import * as fs from 'node:fs';
import * as path from 'node:path';

interface RpcMethod {
  name: string;
  cmd: number;
  inputType: string;
  outputType: string;
}

interface ServiceDef {
  name: string;
  methods: RpcMethod[];
}

function parseProtoSource(protoPath: string): ServiceDef[] {
  const content = fs.readFileSync(protoPath, 'utf-8');
  const services: ServiceDef[] = [];
  const lines = content.split('\n');

  let currentService: ServiceDef | null = null;
  let currentRpcName = '';
  let currentRpcInput = '';
  let currentRpcOutput = '';
  let currentRpcCmd: number | null = null;
  let inRpc = false;

  for (const rawLine of lines) {
    const line = rawLine.trim();

    const svcMatch = line.match(/^service\s+(\w+)\s*\{/);
    if (svcMatch) {
      currentService = { name: svcMatch[1], methods: [] };
      continue;
    }

    if (!currentService) continue;

    // Close of rpc block or service block
    if (line === '}' || line === '};') {
      if (inRpc) {
        if (currentRpcCmd !== null) {
          currentService.methods.push({
            name: currentRpcName,
            cmd: currentRpcCmd,
            inputType: currentRpcInput,
            outputType: currentRpcOutput,
          });
        } else {
          console.warn(`Warning: ${currentService.name}.${currentRpcName} has no (courier.cmd) option, skipping`);
        }
        inRpc = false;
        currentRpcCmd = null;
      } else if (line === '}') {
        services.push(currentService);
        currentService = null;
      }
      continue;
    }

    // RPC declaration
    const rpcMatch = line.match(/^rpc\s+(\w+)\s*\(\s*([^)]+)\s*\)\s*returns\s*\(\s*([^)]+)\s*\)\s*\{?\s*;?\s*$/);
    if (rpcMatch) {
      // Flush previous rpc if any
      if (inRpc && currentRpcCmd !== null && currentService) {
        currentService.methods.push({
          name: currentRpcName,
          cmd: currentRpcCmd,
          inputType: currentRpcInput,
          outputType: currentRpcOutput,
        });
      }

      currentRpcName = rpcMatch[1];
      currentRpcInput = rpcMatch[2].trim();
      currentRpcOutput = rpcMatch[3].trim();
      currentRpcCmd = null;

      // Check if cmd is on the same line
      const cmdOnLine = line.match(/option\s+\(courier\.cmd\)\s*=\s*(\d+)/);
      if (cmdOnLine) {
        currentRpcCmd = parseInt(cmdOnLine[1], 10);
      }

      if (line.includes('{')) {
        inRpc = true;
      } else {
        // Single-line rpc (no braces = no options)
        inRpc = false;
        if (currentRpcCmd !== null && currentService) {
          currentService.methods.push({
            name: currentRpcName,
            cmd: currentRpcCmd,
            inputType: currentRpcInput,
            outputType: currentRpcOutput,
          });
        }
      }
      continue;
    }

    // cmd option inside rpc block
    if (inRpc) {
      const cmdMatch = line.match(/option\s+\(courier\.cmd\)\s*=\s*(\d+)/);
      if (cmdMatch) {
        currentRpcCmd = parseInt(cmdMatch[1], 10);
      }
    }
  }

  return services;
}

function toCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function generateClientCode(services: ServiceDef[], pbImportPath: string): string {
  const lines: string[] = [
    '// Code generated by protoc-gen-courier-js. DO NOT EDIT.',
    '',
    `import { CourierClient } from '@simpossible/courier';`,
  ];

  const messageTypes = new Set<string>();
  for (const svc of services) {
    for (const m of svc.methods) {
      messageTypes.add(m.inputType);
      messageTypes.add(m.outputType);
    }
  }

  if (messageTypes.size > 0) {
    lines.push(`import { ${Array.from(messageTypes).join(', ')} } from '${pbImportPath}';`);
  }
  lines.push('');

  for (const svc of services) {
    lines.push(`export class ${svc.name}Client {`);
    lines.push(`  private client: CourierClient;`);
    lines.push(`  private serviceName = '${svc.name}';`);
    lines.push('');
    lines.push(`  constructor(client: CourierClient) {`);
    lines.push(`    this.client = client;`);
    lines.push(`  }`);

    for (const method of svc.methods) {
      lines.push('');
      lines.push(`  async ${toCamelCase(method.name)}(req: ${method.inputType}): Promise<${method.outputType}> {`);
      lines.push(`    const payload = ${method.inputType}.encode(req).finish();`);
      lines.push(`    const respPayload = await this.client.call(this.serviceName, ${method.cmd}, payload);`);
      lines.push(`    return ${method.outputType}.decode(respPayload);`);
      lines.push(`  }`);
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function main(): void {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.error('Usage: protoc-gen-courier-js <proto-file> [--pb-import <path>] [--out <file>]');
    console.error('');
    console.error('Options:');
    console.error('  --pb-import <path>   Import path for generated protobuf types (default: "./<basename>.pb")');
    console.error('  --out <file>         Output file path (default: stdout)');
    process.exit(1);
  }

  let protoFile = '';
  let pbImport = '';
  let outFile = '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--pb-import' && i + 1 < args.length) {
      pbImport = args[++i];
    } else if (args[i] === '--out' && i + 1 < args.length) {
      outFile = args[++i];
    } else if (!args[i].startsWith('-')) {
      protoFile = args[i];
    }
  }

  if (!protoFile) {
    console.error('Error: no proto file specified');
    process.exit(1);
  }

  const basename = path.basename(protoFile, '.proto');
  if (!pbImport) {
    pbImport = `./${basename}.pb`;
  }

  const services = parseProtoSource(protoFile);

  if (services.length === 0) {
    console.error('Error: no services with courier.cmd options found in ' + protoFile);
    process.exit(1);
  }

  const code = generateClientCode(services, pbImport);

  if (outFile) {
    fs.writeFileSync(outFile, code, 'utf-8');
    console.error(`Generated: ${outFile}`);
  } else {
    process.stdout.write(code);
  }
}

main();
